### ISSUE TITLE
[Enhancement] Support for font weight & font style

### ISSUE THREAD

**Issue by adityakrshnn** [charmy/react-native-stroke-text#10]
Hi, can you add support for `fontWeight` & italic style? 

https://reactnative.dev/docs/text-style-props#fontweight
https://reactnative.dev/docs/text-style-props#fontstyle

**Comment by ozgursoy** [comment]
I added `fontWeight ` before, but there are inconsistencies between platforms, so I removed this feature. fontFamily is enough to handle many cases.
