### ISSUE TITLE
On Android the letters M and W are jumping out according to the size of the strokeWidth

### ISSUE THREAD

**Issue by BMonassa** [charmy/react-native-stroke-text#14]
<img width="92" alt="Captura de Tela 2024-05-14 às 10 54 59" src="https://github.com/charmy/react-native-stroke-text/assets/91953401/e0043f91-59d3-4f38-ae5a-cb0a05b5ba2a">

Would there be any solution?

**Comment by ozgursoy** [comment]
Could you share device info and the font?

**Comment by BMonassa** [comment]
It's happening on all Android devices, whether it's an emulator or cell phone, and I'm using Nunito-Black

**Comment by ozgursoy** [comment]
We have a game in production and using Nunito-Black, There is no problem. Could you share a reproducible example?
Specific fontWeight or fontSize might cause this issue. I need to reproduce to fix the issue.

**Comment by BMonassa** [comment]
Thank's for your time

**Components**
```js
export function UserNameWithStroke({ userName, currentTheme, darkMode, fontSize }) {
	const userNameWidth = Math.min(userName.length * (fontSize / 2), 165);

	return (
		<UserNameStokeContainer style={{ marginVertical: 8 }} fontSize={fontSize} userNameWidth={userNameWidth}>
			<UserNameFill fontSize={fontSize} color={darkMode ? currentTheme.minorDark : currentTheme.minorLight} />
			<StrokeText
				numberOfLines={1}
				text={userName}
				fontSize={fontSize}
				color={darkMode ? 'rgba(0,0,0,1)' : 'rgba(255,255,255,1)'}
				strokeColor={darkMode ? currentTheme.minorDark : currentTheme.minorLight}
				strokeWidth={fontSize / 3}
				fontFamily="Nunito-Black"
				ellipsis={true}
			/>
		</UserNameStokeContainer>
	);
}
```

**Using the component**
```js
<UserNameWithStroke
	userName={props.card.name || 'Your name'}
	currentTheme={theme}
	darkMode={props.darkName === 'dark'}
	fontSize={24}
/>

```

**Comment by ozgursoy** [comment]
Have fun 🎉

 [v1.1.2](https://github.com/charmy/react-native-stroke-text/releases/tag/1.1.2)

**Comment by BMonassa** [comment]
Thanks my brother 🍻
