### ISSUE TITLE
IOS build issue

### ISSUE THREAD

**Issue by Mahato12nikhil** [charmy/react-native-stroke-text#16]
Found two errors:
1. node_modules/@charmy.tech/react-native-stroke-text/ios/StrokeTextView.swift:94:40 Cannot find 'RCTFont' in scope
2. node_modules/@charmy.tech/react-native-stroke-text/ios/StrokeTextView.swift:94:55 'nil' requires a contextual type

**Comment by ozgursoy** [comment]
Have fun 🎉 

https://github.com/charmy/react-native-stroke-text/releases/tag/1.2.2
