### ISSUE TITLE
fontFamily not working with custom google font

### ISSUE THREAD

**Issue by jcboz** [charmy/react-native-stroke-text#2]
Trying to pass a custom fontFamily as the fontFamily parameter to StrokeText component. The font works correctly for other Text components within the same component so I know it is loaded correctly. Not sure if user error or bug with StrokeText. 

```
text: {
    color: 'white',
    fontFamily: 'Shrikhand_400Regular',
    fontSize: 96,
  },
```

```
<View>
        <Text style={styles.text}>Hello</Text>
        <StrokeText
          text="Hello"
          fontSize={96}
          color="#ffffff"
          strokeColor="#000000"
          strokeWidth={5}
          fontFamily="Shrikhand_400Regular"
        />
</View>
```

First "Hello" is the expected font, "Hello" in StrokeText is not. Loading in fonts like so:

```
import { Shrikhand_400Regular, useFonts } from '@expo-google-fonts/shrikhand';

  const [fontsLoaded, fontError] = useFonts({
    Shrikhand_400Regular,
  });
```

**Comment by ozgursoy** [comment]
Hi,

You can't use like that. I didn't develop the library for expo. I have to check what's going on native side. 

https://github.com/expo/expo/tree/master/packages/expo-font
I quickly checked the `expo-font`. It looks like fonts are loaded at runtime. 

Maybe I can implement that by passing the custom expo font to `StrokeText`

I am super busy a few weeks, maybe I can implement that feature later, cause there is no way to use stroked texts on React Native.
Expo support would be nice for React Native community.

**Comment by jcboz** [comment]
Ohh I see. Thank you for the reply! I look forward to the implementation

**Comment by micky37** [comment]
Hello, I have the same problem with a custom font in .otf, I also use Expo, were you able to make any progress on the problem?

Sincerely,

**Comment by ozgursoy** [comment]
Have fun 🎉

[1.2.0](https://github.com/charmy/react-native-stroke-text/releases/tag/1.2.0)
