### ISSUE TITLE
Usage with Expo

### ISSUE THREAD

**Issue by Marvelousy20** [charmy/react-native-stroke-text#20]
Great tool, is there an idea how to use this package in expo?

**Comment by ozgursoy** [comment]
`yarn add @charmy.tech/react-native-stroke-text` that's it

If you want to use custom font
[Custom Font Configuration](https://github.com/charmy/react-native-stroke-text?tab=readme-ov-file#expo-expo-font)

**Comment by algarcia-vector** [comment]
this is not working with expo, i am getting this error: 
![Screenshot 2024-08-08 at 2 04 22 a m](https://github.com/user-attachments/assets/14110572-dbec-4267-91e4-0f936af4671b)

**Comment by ozgursoy** [comment]
It's a native library not a js library, you can't use with expo go. You need to build native side otherwise you'll see this error.
