### ISSUE TITLE
[Question] Doesn't work with Reanimated?

### ISSUE THREAD

**Issue by adityakrshnn** [charmy/react-native-stroke-text#7]
Hi,

I am trying to use `useAnimatedProps` from react-native-reanimated to your `StrokeText` but it doesn't update when the prop's value updates once the StrokeText is initialized. It does take the initial value from the same hook so I know the hook is providing the initial prop value but StrokeText doesn't rerender on subsequent new props. I can provide a codesandbox link if needed. Any ideas?

Some context:

`AnimatedStrokeText` component so that reanimated is able to provide props to it.
```
import { StrokeText } from "@charmy.tech/react-native-stroke-text";
import { forwardRef } from "react";
import Animated from "react-native-reanimated";

export const AnimatedStrokeText = Animated.createAnimatedComponent(
  forwardRef(StrokeText),
);
```
The `useAnimatedProps` hook
```
const strokeWidthProps = useAnimatedProps(() => {
  const strokeWidth = interpolate(
    Easing.linear(timer.value),
    [
      0,
      200,
      1000,
      2000,
    ],
    [1, 1, 3, 3],
    Extrapolation.CLAMP,
  );

  return {
    strokeWidth,
  };
}
```

The usage:
```
<AnimatedStrokeText
  text="Hello World"
  fontSize={20}
  color="#00FF00"
  strokeColor="#000000"
  fontFamily="Arial Rounded MT Bold"
  animatedProps={strokeWidthProps}
/>
```

I have tested similar code on a simple text and it works but not with `StrokeText`. Let me know if you know why

**Comment by ozgursoy** [comment]
Have fun 🎉

https://github.com/charmy/react-native-stroke-text/releases/tag/1.0.8

I recommend to use `width` prop to animate like that, when `strokeWidth` changed, calculates the width again so might cause flicker.

In the video on the right side, the width prop is not set, so it flickers.

https://github.com/charmy/react-native-stroke-text/assets/13810383/33af0001-b095-4a2f-a43b-2dcb82d5e356

**Comment by adityakrshnn** [comment]
Thanks it works great with `strokeWidth` & `strokeColor`. I think `color` prop still doesn't take in changes. Can you make the same change for `color` prop?
